### ISSUE TITLE
question: need to move the source code of git-init here?

### ISSUE THREAD

**Issue by l-qing** [tektoncd-catalog/git-clone#2]
The code for git-init has been removed in this pull request: https://github.com/tektoncd/pipeline/pull/6417

In [TEP-0074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md), it's mentioned that we need to move the code to this code repository?
`Code for the "git-init" image will be moved into the tektoncd-catalog/git-clone repo.`

However, this code repository is still very clean at the moment. 😁

**Comment by QuanZhang-William** [comment]
Hi @l-qing and @liangyuanpeng. Yeah, you are right. The `git-init` image will be moved to this repo, but we haven't started the migration yet.

Repos under this org is still in "Work in Process" state and is not ready to be used. I will update the org README file to reflect this.

/cc @ywluogg

**Comment by l-qing** [comment]
done
